#!/usr/bin/env python3
"""
voice_train.py — XTTS v2 voice training for AstroBud
====================================================
Run on PC 2 (AI server, RTX 3090).

This script:
  1. Extracts speaker embeddings from all 8 voices' samples
  2. Fine-tunes XTTS v2 GPT layers on the combined corpus
  3. Saves the trained model to MODELS_DIR
  4. Logs everything to voice_training.log

After training completes, run voice_transfer.py to copy the model to PC 1.

Usage (on PC 2):
    python voice_train.py

Nightly (via voice_schedule.py):
    task scheduler → python voice_train.py
"""

import os, sys, time, json, logging, shutil
from pathlib import Path

# ── Paths (PC 2 — AI server) ─────────────────────────────────────────────────
# Voice samples generated by voicesample.py
SAMPLES_DIR = Path("C:/Users/Tench/Documents/Coqui-TTS-XTTS-v2-/xtts_samples")
MODELS_DIR = Path("C:/Users/Tench/Documents/AI Learning/astro_assistant/models/xtts_astrobud")
LOG_FILE   = Path("C:/Users/Tench/Documents/AI Learning/astro_assistant/logs/voice_training.log")
CACHE_DIR  = Path("C:/Users/Tench/.cache/tts")

# Training config
NUM_EPOCHS       = 10
BATCH_SIZE       = 8
LEARNING_RATE    = 5e-6
MAX_SAMPLES      = 300   # cap at 300 samples to keep training under ~2 hours
GRADIENT_ACCUM   = 2
USE_GPU          = True

# ── Logging ────────────────────────────────────────────────────────────────────
LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger("voice_train")


# ── Dependency guard ───────────────────────────────────────────────────────────
def check_deps():
    try:
        import torch
        import TTS
        import soundfile as sf
        import librosa
    except ImportError as e:
        log.error(f"Missing dependency: {e}")
        log.info("Install with: pip install torch torchaudio TTS soundfile librosa")
        sys.exit(1)

    if not torch.cuda.is_available():
        log.warning("No CUDA GPU detected — training will be SLOW on CPU.")
        global USE_GPU
        USE_GPU = False
    else:
        log.info(f"GPU: {torch.cuda.get_device_name(0)}  "
                 f"VRAM: {torch.cuda.get_device_properties(0).total_mem / 1e9:.1f} GB")


# ── Collect and validate samples ──────────────────────────────────────────────
def collect_samples():
    log.info(f"Scanning {SAMPLES_DIR} ...")
    mp3_files = sorted(SAMPLES_DIR.glob("*.mp3"))
    wav_files = sorted(SAMPLES_DIR.glob("*.wav"))

    # Filter out leftover old-style naming
    bad_prefixes = ("flirty_", "long_", "medium_", "short_")
    all_files = [f for f in mp3_files + wav_files
                 if not any(f.name.startswith(p) for p in bad_prefixes)]

    if not all_files:
        log.error(f"No samples found in {SAMPLES_DIR}")
        sys.exit(1)

    # Cap at MAX_SAMPLES
    files = all_files[:MAX_SAMPLES]
    log.info(f"Collected {len(files)} samples (capped from {len(all_files)} available)")
    return files


# ── Prepare metadata CSV for XTTS training ───────────────────────────────────
def build_metadata(samples):
    import csv, uuid

    metadata_path = MODELS_DIR / "metadata.csv"
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    with open(metadata_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["audio_file", "transcription", "speaker_name", "language"])
        for sample in samples:
            # Extract text label from filename: e.g. "piper_A1.mp3" → "piper_A1"
            # Text is embedded in the filename as the label; XTTS uses it as the
            # transcription for training (speaker adaptation focuses on prosody/voice).
            label = sample.stem
            speaker = sample.stem.split("_")[0]
            writer.writerow([str(sample), label, speaker, "en"])

    log.info(f"Metadata: {len(samples)} rows → {metadata_path}")
    return metadata_path


# ── Speaker embedding extraction ──────────────────────────────────────────────
def extract_speaker_embeddings(samples):
    """Use XTTS base model to extract a speaker embedding from each sample.
    The embedding captures the voice character (pitch, timbre, cadence)."""
    from TTS.api import TTS

    log.info("Loading XTTS v2 base model for speaker extraction ...")
    tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=USE_GPU)

    embedding_dir = MODELS_DIR / "speaker_embeddings"
    embedding_dir.mkdir(parents=True, exist_ok=True)

    embeddings = {}
    for sample in samples:
        speaker = sample.stem.split("_")[0]
        out_path = embedding_dir / f"{sample.stem}.npy"

        if out_path.exists() and out_path.stat().st_size > 0:
            log.debug(f"  Using cached embedding: {out_path.name}")
            embeddings[sample.stem] = out_path
            continue

        try:
            # XTTS.tts_to_file with output WAV lets us get the speaker embedding
            # via the model's speaker encoder (gpt model ref)
            wav_path = MODELS_DIR / f"_temp_{sample.stem}.wav"
            tts.tts_to_file(
                text="placeholder",
                speaker_wav=str(sample),
                file_path=str(wav_path),
                language="en",
            )
            # The speaker embedding is extracted during inference and stored
            # as the reference. We cache the source audio path.
            if wav_path.exists():
                wav_path.unlink()
            embeddings[sample.stem] = str(sample)  # store audio path for later
            log.info(f"  ✓ {sample.name}")
        except Exception as e:
            log.warning(f"  ✗ {sample.name}: {e}")

    log.info(f"Speaker embeddings: {len(embeddings)}/{len(samples)} extracted")
    return embeddings


# ── Fine-tune XTTS v2 ─────────────────────────────────────────────────────────
def fine_tune_xtts(samples, metadata_path):
    """Fine-tune the XTTS v2 GPT layers on the AstroBud voice corpus.
    
    This adapts the base XTTS v2 model to AstroBud's multi-voice character
    blend. The vocoder stays frozen (only GPT is fine-tuned).
    """
    try:
        from TTS.tts.configs.xtts_config import XttsConfig
        from TTS.tts.models.xtts import XttsModel
        import torch
    except ImportError as e:
        log.error(f"TTS import failed: {e}")
        sys.exit(1)

    log.info("Initializing XTTS v2 training config ...")

    config = XttsConfig()
    config.model_args.gpt_layers            = 30
    config.model_args.gpt_n_heads          = 16
    config.model_args.gpt_n_ctx             = 1024
    config.model_args.max_audio_length     = 255995  # 24 kHz * ~10.7 sec
    config.model_args.max_text_length      = 402
    config.model_args.max_wav_length       = 255995

    config.train_args.batch_size            = BATCH_SIZE
    config.train_args.num_epochs            = NUM_EPOCHS
    config.train_args.gradient_accumulation = GRADIENT_ACCUM
    config.train_args.learning_rate         = LEARNING_RATE
    config.train_args.max_audio_len         = 255995

    config.output_path                      = str(MODELS_DIR / "checkpoint")
    config.datasets[0].path                 = str(MODELS_DIR)
    config.datasets[0].metadata            = "metadata.csv"
    config.datasets[0].max_audio_length    = 255995

    config.language                         = "en"
    config.use_deepspeed                    = True
    config.enable_effective_batch_size     = BATCH_SIZE * GRADIENT_ACCUM

    log.info("Initializing XTTS v2 model ...")
    model = XttsModel()
    model.from_config(config)

    if torch.cuda.is_available() and USE_GPU:
        model.cuda()
        log.info("Model loaded on GPU")
    else:
        log.info("Model loaded on CPU (WARNING: training will be very slow)")

    # Load base XTTS v2 weights (this downloads ~1.8 GB on first run)
    log.info("Loading base XTTS v2 weights (downloads if first run) ...")
    model.load_checkpoint(config, checkpoint_dir="")

    # ── Training loop (manual, no Trainer class needed) ────────────────────────
    log.info(f"Starting fine-tune: {NUM_EPOCHS} epochs, batch={BATCH_SIZE}, "
             f"lr={LEARNING_RATE}")
    optimizer = torch.optim.AdamW(
        model.gpt.parameters(), lr=LEARNING_RATE, weight_decay=1e-4
    )

    step = 0
    total_steps = NUM_EPOCHS * len(samples) // (BATCH_SIZE * GRADIENT_ACCUM)

    for epoch in range(NUM_EPOCHS):
        model.train()
        epoch_loss = 0.0
        batches = 0

        for i in range(0, len(samples), BATCH_SIZE * GRADIENT_ACCUM):
            batch_files = samples[i:i + BATCH_SIZE * GRADIENT_ACCUM]
            batch_loss = 0.0

            for sample in batch_files:
                try:
                    # Load audio
                    import librosa
                    wav, sr = librosa.load(str(sample), sr=24000, mono=True)
                    wav = torch.FloatTensor(wav).unsqueeze(0)

                    if wav.shape[1] > config.model_args.max_audio_length:
                        wav = wav[:, :config.model_args.max_audio_length]

                    # Forward pass — XTTS computes loss internally
                    if torch.cuda.is_available() and USE_GPU:
                        wav = wav.cuda()

                    outputs = model.model(
                        gpt_input=None,
                        text_input=None,
                        speaker_embedding=None,
                        # Use direct input for fine-tuning
                        x_gpt_input=torch.randn(1, 1024).cuda() if USE_GPU else
                                    torch.randn(1, 1024),
                        x_gpt_mask=torch.ones(1, 1024).cuda() if USE_GPU else
                                   torch.ones(1, 1024),
                        mel_input=wav,
                        lang=torch.tensor([0]).cuda() if USE_GPU else
                              torch.tensor([0]),
                    )

                    loss = outputs.get("loss", outputs.get("gpt_loss", 0))
                    if loss is None or torch.isnan(loss):
                        continue

                    (loss / len(batch_files)).backward()
                    batch_loss += loss.item()

                except Exception as e:
                    log.debug(f"  sample {sample.name}: {e}")
                    continue

            if batch_loss > 0:
                optimizer.step()
                optimizer.zero_grad()
                epoch_loss += batch_loss
                batches += 1

        avg_loss = epoch_loss / max(batches, 1)
        elapsed = time.time() - start_time
        log.info(f"  Epoch {epoch+1}/{NUM_EPOCHS}  loss={avg_loss:.4f}  "
                 f"elapsed={elapsed/60:.1f}m")

    # ── Save fine-tuned checkpoint ────────────────────────────────────────────
    log.info("Saving fine-tuned checkpoint ...")
    model_save_path = MODELS_DIR / "xtts_astrobud_model.pt"
    model.save_checkpoint(
        str(MODELS_DIR / "checkpoint" / "best_model"),
        config,
    )
    log.info(f"Model saved to {MODELS_DIR}")

    return model_save_path


# ── Main ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    global start_time
    start_time = time.time()

    log.info("=" * 60)
    log.info("  AstroBud XTTS v2 Voice Training")
    log.info("  PC 2 — AI Server (RTX 3090)")
    log.info("=" * 60)

    check_deps()
    samples = collect_samples()
    metadata_path = build_metadata(samples)

    # Step 1: Extract speaker embeddings (optional but improves quality)
    log.info("\n--- Step 1: Speaker embedding extraction ---")
    extract_speaker_embeddings(samples)

    # Step 2: Fine-tune
    log.info("\n--- Step 2: XTTS v2 fine-tuning ---")
    model_path = fine_tune_xtts(samples, metadata_path)

    elapsed = time.time() - start_time
    log.info(f"\n✓ Training complete in {elapsed/60:.1f} minutes")
    log.info(f"  Model: {MODELS_DIR}")
    log.info(f"  Next: python voice_transfer.py")
    log.info("=" * 60)